### ISSUE TITLE
Broken show pages

### ISSUE THREAD

**Issue by StrPlayer** [stpnwf/ZestyTheme#4] opened 2024-06-05 08:38 UTC
**Describe the bug**
half of the show pages are broken

**To Reproduce**
1. update jellyfin to 10.9.4
2. it broke :(

**On a Smartphone or Tablet?**
 - Windows chrome
 - Windows jellyfin media player
 - Samsung S22

**Are you using any extra code in your "Custom CSS" field?**
no just color change from ur github

**Screenshots**
A picture is worth a thousand words...
![image](https://github.com/stpnwf/ZestyTheme/assets/68419913/123ba19b-1022-4467-94de-baf8500f8341)
![photo_2024-06-05_03-35-16](https://github.com/stpnwf/ZestyTheme/assets/68419913/9e597b3c-2a51-4a8c-a4e3-8a2fbc2b015d)

**Comment by stpnwf** [comment] 2024-06-05 12:41
Regarding the first picture, can you check that you have backdrops enabled? (Settings > Display > Backdrops) That is what usually happens when you have it disabled.

Regarding the second pic, that _may_ have been me, as I made a push with a typo when I was adding tablet support, but have since fixed it. Maybe the changes haven't made to the cdn url yet (as it does take a bit). Can you please paste the contents of theme.css into your custom CSS field and see if you still have the issue?

I still haven't updated to 10.9.4, so I can't test it on my end.

**Comment by hackmonker** [comment] 2024-06-05 17:44
currently on 10.9.4 and can confirm that the clear logo bug is still present in mobile view. the logo come below

**Comment by stpnwf** [comment] 2024-06-05 20:54
Ok, and can you confirm you are using the contents from `theme.css` into your Custom CSS instead of the one line import?

**Comment by StrPlayer** [comment] 2024-06-05 22:07
yes i used the import url and i copy pasted the whole theme.css code in and it still broken

**Comment by StrPlayer** [comment] 2024-06-05 22:07
even the show pages are still broken
![image](https://github.com/stpnwf/ZestyTheme/assets/68419913/86ff584f-0e86-4831-adf3-c3bf10539fac)

**Comment by stpnwf** [comment] 2024-06-05 22:55
Ok, thanks for the feedback, I saw 10.9.5 just came out. Can anyone confirm it also happens on it?

**Comment by StrPlayer** [comment] 2024-06-05 22:57
i didnt update yet so i cant tell u

**Comment by StrPlayer** [comment] 2024-06-06 19:46
bug is still a thing in 10.9.6

**Comment by stpnwf** [comment] 2024-06-07 01:08
Damn, there is already a 10.9.6? I wanna wait a few days since an update is out to see if there aren't any huge bugs before I update. Last time I updated from 10.8.12 to 10.9.1 it borked my server and I had to create another container from scratch and set everything up again...

**Comment by stpnwf** [comment] 2024-08-28 00:13
Hey guys, my bad on not replying earlier. I have been busy and I had issue with my server and was only able to get it back working now. I am now running on 10.9.10 and I don't have the issues show here. I will update the mobile movie/show page bc it currently looks a little broken, but these issues reported here specifically I could never reproduce.

The black bar happens when backdrops are not enabled in Settings > Display > Backdrops. Can anyone still report having these issues still?

**Comment by stpnwf** [comment] 2024-09-30 20:06
Closing this. Feel free to reopen if you still have this issue.

**Closed by stpnwf** 2024-09-30 20:06 UTC
